### PR TITLE
fix: add periodic APIService reconciler

### LINKED ISSUE #327: APIService cleanup on SIGTERM breaks multi-replica deployments
When a reports-server pod receives SIGTERM (rolling update, scale-down, node drain), CleanupApiServices() patches all APIService objects to remove spec.service, making them Local:
https://github.com/kyverno/reports-server/blob/main/pkg/app/policyserver.go#L86-L92
https://github.com/kyverno/reports-server/blob/main/pkg/server/config.go#L216-L234

With replicas > 1 or autoscaling enabled, this causes a race condition:
1. Pod A is terminated (e.g. during a rolling update)
2. Pod A's shutdown hook patches spec.service to null on all APIServices
3. Pod B is still running but has no reconciliation loop to restore spec.service
4. All report resources become unavailable (the server could not find the requested resource)
5. Only a pod restart fixes it, since installApiServices() only runs at startup

This is especially problematic because the Helm chart ships with an HPA option. The APIService is uninstalled on the HPA scaling down, causing the reports server do not handle requests and CPU usage going down. The HPA never scales up and the APIService is definitely uninstalled.

A few suggestions are:
- Expose a flag/Helm value to disable the APIService cleanup on shutdown (e.g. --cleanup-apiservices-on-shutdown=false)
- Add a reconciliation loop so remaining replicas can restore spec.service
- Use leader election so only the last replica cleans up
- At minimum, document that replicas > 1 / HPA is unsafe, or remove HPA from the chart until this is fixed

### PR DESCRIPTION
**Pull request by fernandezcuesta**
During rolling updates, the running pod cleanup hook patches `spec.service` to null on all APIServices.
However, the running pods have no way to detect or repair this since `installApiServices()` only ran once at startup, making aggregated report resources unavailable until restart in a sort of chicken-egg scenario.

Fixes: #327

### CODE REVIEW

File: pkg/server/config.go [hunk 1]
```diff
@@ -213,6 +214,28 @@ func (c *Config) installApiServices() error {
 	return nil
 }
 
+func (c *Config) StartAPIServiceReconciler(ctx context.Context) {
+	if !c.APIServices.StoreReports && !c.APIServices.StoreEphemeralReports && !c.APIServices.StoreOpenreports {
+		klog.Info("No APIServices enabled, skipping reconciler")
+		return
+	}
+	const reconcileInterval = 10 * time.Second
```
Comment (aerosouund) [inline pkg/server/config.go]: Can we make this value configurable ?

**Review by aerosouund — DISMISSED** [review]

**Review by aerosouund — APPROVED** [review]

**Comment by JorTurFer** [comment]
Hello
Do you have any expected release date for this?
